---
- name: template nginx.conf
  become: true
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: "u=rw,g=rw,o=r"
    owner: "nginx"
    group: "nginx"
  notify: restart nginx

- name: sites-enabled exist
  become: true
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled
    state: directory
    recurse: true
    mode: "u=rwx,g=rwx,o=rx"
    owner: "nginx"
    group: "nginx"

- name: template proxy site
  become: true
  ansible.builtin.template:
    src: "mux-site.j2"
    dest: "/etc/nginx/sites-enabled/{{ nginx_rp.name }}"
    mode: "u=rw,g=rw,o=r"
    owner: "nginx"
    group: "nginx"
  notify: restart nginx

- name: template domain proxied sites
  become: true
  ansible.builtin.template:
    src: "site.j2"
    dest: "/etc/nginx/sites-enabled/{{ site.name }}"
    mode: "u=rw,g=rw,o=r"
    owner: "nginx"
    group: "nginx"
  notify: restart nginx
  loop: "{{ nginx_rp.domain }}"
  loop_control:
    loop_var: site
